### ISSUE TITLE
Not compiling as  `deranged`  uses `std`

### ISSUE THREAD

**Issue by tolik518** [Anders429/gba_clock#1]
Hey, 
I just wanted to let you know that it seems like it's not possible to use the library in a gba project as one of the dependencies  `deranged`, is using `std`.

```rust
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv4t-none-eabi` target may not support the standard library
  = note: `std` is required by `deranged` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

**Comment by Anders429** [comment]
Hmm, that's definitely unexpected! I have default features disabled for it here: https://github.com/Anders429/gba_clock/blob/b213e1ca5d5f0e761959b125cd8c28d50e5f1849/Cargo.toml#L14. I have previously used this library in a project of my own and not had any issues, but maybe something has changed in some recent release to break it? I'm currently on mobile, so I can't sanity check it. 

One thing to look at: are you also pulling in the `time` crate? If so, you need to disable its default features as well. `time`'s `std` feature enables `deranged`'s `std` feature: https://github.com/time-rs/time/blob/main/time/Cargo.toml#L46

**Comment by tolik518** [comment]
@Anders429 Oh yes, that might have been me not configuring the `time` dependency properly! 
Thank you for the fast reaction :)

Edit: Yep, the issue was because of the `time` crate. I'd suggest maybe adding a small `Cargo.toml`-snippet where the needed crates are included for the example to work? This would ensure that never Rust users won't encounter this problem

**Comment by Anders429** [comment]
Glad you were able to resolve it! Yes, I think you're right that adding something to the README would help. I might also consider re-exporting the used types from `time` directly so that users don't have to worry about importing two crates directly.
